Repository wecode-bootcamp-korea/33-2nd-MegaBoxu-frontend, pull requests merged in 2022-06, with the labels that each got.

#8 [33기 이해용] ADD: theme.js 파일 업로드합니다.
  src/styles/theme.js
Labels: Rebase 요청

#6 [33기] 김형석 ADD : booking page layout 완료 및 date slide 기능 구현 query string 필터 기능 구현
  package-lock.json
  package.json
  public/data/bookingData.json
  public/images/마녀.jpg
  public/images/범죄도시2.jpg
  public/images/브로커.jpg
  public/images/쥬라기월드.jpg
  public/images/포켓몬스터.jpg
  src/pages/Booking/Booking.js
  src/pages/Booking/components/BookingBox.js
  src/pages/Booking/components/Date/BookingDate.js
  src/pages/Booking/components/Date/components/DateBox.js
  src/pages/Booking/components/Date/components/YearMonth.js
  src/pages/Booking/components/Movie/BookingMovie.js
  src/pages/Booking/components/Movie/components/MovieLists.js
  src/pages/Booking/components/Movie/components/MoviePosts.js
  src/pages/Booking/components/Theater/BookingTheater.js
  src/pages/Booking/components/Theater/components/RegionLists.js
  src/pages/Booking/components/Theater/components/TheaterLists.js
  src/pages/Booking/components/Theater/components/TheaterPosts.js
  src/pages/Booking/components/Time/BookingTime.js
  src/pages/Booking/components/Time/components/MovieTimes.js
  yarn.lock
Labels: 멘토 리뷰 요청

#4 [33기 이해용] Add: 메인 페이지 conflict 해결 완료
  package-lock.json
  package.json
  public/data/movieCarouselData.json
  public/images/Main/theater.jpg
  public/images/megaboxu.png
  public/index.html
  src/Router.js
  src/hooks/useFetch.js
  src/pages/Main/Main.js
  src/pages/Main/components/BoxOfficeCarousel.js
  src/pages/Main/components/InfoMegaboxu.js
  src/pages/Main/components/MegaboxuOpen.js
  src/pages/Main/components/Membership.js
  src/pages/Main/components/MembershipStore.js
  src/pages/Main/components/MovieCarousel.js
  src/pages/Main/components/TimetableBooking.js
Labels: Rebase 요청

#10 [33기] 김형석 Modify : API별 fetch 나누기 , 서버와 데이터 통신 완료
  package-lock.json
  package.json
  public/data/bookingData.json
  public/data/theaterData.json
  public/data/timeTable.json
  src/pages/Booking/components/BookingBox.js
  src/pages/Booking/components/Date/BookingDate.js
  src/pages/Booking/components/Movie/BookingMovie.js
  src/pages/Booking/components/Movie/components/MovieLists.js
  src/pages/Booking/components/Movie/components/MoviePosts.js
  src/pages/Booking/components/Theater/BookingTheater.js
  src/pages/Booking/components/Theater/components/RegionLists.js
  src/pages/Booking/components/Theater/components/TheaterLists.js
  src/pages/Booking/components/Theater/components/TheaterPosts.js
  src/pages/Booking/components/Time/components/MovieTimes.js
  yarn.lock
Labels: 멘토 리뷰 요청

#7 [33기 이해용] ADD: Login page conflict 해결 했습니다.
  .gitignore
  package-lock.json
  src/Router.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Login/components/KakaoLogin.js
  src/pages/Login/components/KakaoLoginAuth.js
  src/pages/Login/components/LoginBody.js
  src/pages/Login/components/LoginHeader.js
  src/pages/Login/components/LoginModal.js
Labels: 멘토 리뷰 요청

#1 [33기 노해리] Add: Footer 레이아웃
  package-lock.json
  public/images/megaboxu3.png
  src/components/Footer/Footer.js
  src/components/Footer/components/FooterInfo.js
  src/components/Footer/components/FooterText.js
  yarn.lock
Labels: 멘토 리뷰 요청

#3 [33기 노해리] Add: Nav 레이아웃 완료
  public/images/megaboxu1.png
  public/images/megaboxu2.png
  src/components/Nav/LoginBox/LoginBox.js
  src/components/Nav/MovieChart/MovieChart.js
  src/components/Nav/Nav.js
  src/components/Nav/NavLeft/NavLeftDropLi.js
  src/components/Nav/NavLeft/NavLeftMenu.js
  src/components/Nav/NavRight/NavRightDropLi.js
  src/components/Nav/NavRight/NavRightMenu.js
  src/components/Nav/SearchBox/SearchBox.js
  src/components/Nav/SiteMap/SiteMap.js
  src/components/Nav/SiteMap/SiteMapContent.js
  src/pages/Booking/components/BookingBox.js
Labels: 수정 요청

#9 [33기 노해리] Modify: 영화 리스트 기능 구현
  public/data/MovieList.json
  public/images/Facetune_22-12-2021-17-16-54.jpg
  public/images/iOS 이미지 (31).jpg
  public/images/iOS 이미지.jpg
  src/pages/MovieList/MovieList.js
  src/pages/MovieList/component/MoreButton.js
  src/pages/MovieList/component/MovieCategory.js
  src/pages/MovieList/component/MovieContent.js
  src/pages/MovieList/component/MovieFilterBox.js
  src/pages/MovieList/component/MovieSearchBox.js
Labels: 멘토 리뷰 요청
